apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-nginx
  template:
    metadata:
      labels:
        app: frontend-nginx
    spec:
      containers:
      - name: frontend-nginx
        image: chatodo/frontend-nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend-nginx

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: web-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - flask-gateway
  http:
  - match:
    - uri:
        exact: "/"
    - uri:
        prefix: "/admin.html"
    route:
    - destination:
        host: frontend-nginx.default.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/api"
    route:
    - destination:
        host: flask-api.default.svc.cluster.local
        port:
          number: 5000