CREATE DATABASE dbflask;
USE dbflask;

CREATE TABLE utilisateurs (
	id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL
	is_admin BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE produits (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nom VARCHAR(255) NOT NULL,
	prix DECIMAL(10, 2) NOT NULL,
	stock INT NOT NULL DEFAULT 0
);